export {
	type AgentCandidate,
	type AgentCommandResult,
	type AgentFile,
	type AgentMessage,
	type AgentMessageGroup,
	type AgentOmission,
	type AgentSkip,
	type AgentStatus,
	type AgentThread,
	type AgentTimelineItem,
	projectAgentResult,
} from "./agent.ts";
export {
	type ConfiguredChannel,
	type ConfiguredDirectMessage,
	type LoadConfigOptions,
	type LocalMattermostConfig,
	loadMattermostConfig,
	type MattermostConfig,
	normalizeMattermostUrl,
	type OutputBudgets,
	requireMattermostToken,
} from "./config.ts";
export {
	type ContextClient,
	type ContextDependencies,
	type ContextInput,
	type ContextResult,
	type ContextThread,
	type FreshnessEvidence,
	getMattermostContext,
	getMattermostThread,
	type RemoteSearchEvidence,
	type SearchContextResult,
	type SearchFilterInput,
	type SearchFilters,
	type SearchInput,
	searchMattermost,
	type ThreadInput,
	type ThreadResult,
} from "./context.ts";
export {
	type ChannelsResultV1,
	type ChannelsValidateResultV1,
	type CommandResultV1,
	type ContextCommandResultV1,
	channelsResultV1Schema,
	channelsValidateResultV1Schema,
	commandResultV1Schema,
	contextResultV1Schema,
	type DoctorResultV1,
	doctorResultV1Schema,
	type FileCommandResultV1,
	failureResultV1Schema,
	fileResultV1Schema,
	parseCommandResultV1,
	type SearchCommandResultV1,
	type SyncCommandResultV1,
	searchResultV1Schema,
	syncResultV1Schema,
	type ThreadCommandResultV1,
	threadResultV1Schema,
	type WhoamiResultV1,
	whoamiResultV1Schema,
} from "./contracts.ts";
export {
	type EngineeringEntity,
	type EngineeringEntityKind,
	extractEngineeringEntities,
} from "./entities.ts";
export {
	AppError,
	ConfigError,
	DatabaseError,
	type ErrorSource,
} from "./errors.ts";
export {
	type ChannelPostOptions,
	MattermostApiError,
	MattermostClient,
	type MattermostClientOptions,
	type TeamPostSearchOptions,
} from "./mattermost/client.ts";
export type {
	MattermostChannel,
	MattermostFileInfo,
	MattermostPost,
	MattermostPostList,
	MattermostTeam,
	MattermostUser,
} from "./mattermost/schemas.ts";
export {
	buildTimeline,
	type EvidenceAttachment,
	type EvidencePost,
	type PackedPost,
	type PackedThread,
	type PackSkip,
	type PackThreadOptions,
	type PackTimelineItem,
	packThread,
	renderedAttachmentUnits,
	renderedPostUnits,
} from "./packing.ts";
export {
	expandQueryTerms,
	matchesQueryExpansion,
	type QueryExpansion,
	type QueryExpansionKind,
} from "./query-expansion.ts";
export {
	type CommandResult,
	SCHEMA_VERSION,
	type StableError,
	type Warning,
} from "./results.ts";
export {
	type AgentProbeInput,
	type AgentProbeKind,
	classifySubject,
	configuredConversations,
	directCandidate,
	type LexicalMatchEvidence,
	type MattermostSubject,
	type RankFusionContribution,
	type RankingReason,
	type RetrievalProbe,
	type RoutedConversation,
	type RoutingEvidenceType,
	type RoutingResult,
	RRF_RANK_CONSTANT,
	reciprocalRankFusionScore,
	remoteSearchCandidate,
	resolveProbes,
	routeConversations,
	type SearchMatch,
	type SearchResult,
	type StructuredSearchMatch,
	searchThreads,
	type ThreadCandidate,
	type ThreadRankingEvidence,
	widenedRouting,
} from "./retrieval.ts";
export {
	type ChannelValidationResult,
	type ConfiguredConversationsResult,
	type ConfiguredDirectMessageResult,
	type DoctorCheck,
	type DoctorResult,
	listConfiguredConversations,
	runDoctor,
	type ValidationItem,
	validateConfiguredConversations,
} from "./setup.ts";
export {
	buildFtsProbe,
	buildFtsQuery,
	type ConversationKind,
	type ConversationRecord,
	databaseFilePaths,
	type IndexedFile,
	type IndexedPost,
	type IndexedUser,
	type LexicalHit,
	type LexicalRetrievalSource,
	type LexicalSearchOptions,
	MattermostStore,
	type PageWrite,
	type StructuredEntityHit,
	type StructuredEntityRecord,
	type SyncCheckpoint,
	type ThreadSearchFilters,
	type TicketThreadRelationship,
} from "./storage.ts";
export {
	type ConversationFreshness,
	type ConversationSyncResult,
	inspectFreshness,
	reconcileStaleConversations,
	resolveConversations,
	type SyncClient,
	type SyncOptions,
	type SyncResult,
	syncConfiguredConversations,
} from "./sync.ts";
export {
	containsNormalizedText,
	normalizeSearchText,
	STOP_WORDS,
} from "./text.ts";
