export {
	type AgentCandidate,
	type AgentCommandResult,
	type AgentEvidenceIssue,
	type AgentFile,
	type AgentOmission,
	type AgentPost,
	type AgentStatus,
	type AgentThread,
	projectAgentResult,
} from "./agent.ts";
export {
	type ConfiguredChannel,
	type ConfiguredDirectMessage,
	type LoadConfigOptions,
	type LocalMattermostConfig,
	loadMattermostConfig,
	type MattermostConfig,
	normalizeMattermostUrl,
	type OutputBudgets,
	requireMattermostToken,
} from "./config.ts";
export {
	type ContextClient,
	type ContextDependencies,
	type ContextInput,
	type ContextResult,
	type ContextThread,
	type FreshnessEvidence,
	getMattermostContext,
	getMattermostThread,
	type SearchContextResult,
	type SearchInput,
	searchMattermost,
	type ThreadInput,
	type ThreadResult,
} from "./context.ts";
export {
	type ChannelsResultV1,
	type ChannelsValidateResultV1,
	type CommandResultV1,
	type ContextCommandResultV1,
	channelsResultV1Schema,
	channelsValidateResultV1Schema,
	commandResultV1Schema,
	contextResultV1Schema,
	type DoctorResultV1,
	doctorResultV1Schema,
	failureResultV1Schema,
	parseCommandResultV1,
	type SearchCommandResultV1,
	type SyncCommandResultV1,
	searchResultV1Schema,
	syncResultV1Schema,
	type ThreadCommandResultV1,
	threadResultV1Schema,
	type WhoamiResultV1,
	whoamiResultV1Schema,
} from "./contracts.ts";
export {
	AppError,
	ConfigError,
	DatabaseError,
	type ErrorSource,
} from "./errors.ts";
export {
	type ChannelPostOptions,
	MattermostApiError,
	MattermostClient,
	type MattermostClientOptions,
} from "./mattermost/client.ts";
export type {
	MattermostChannel,
	MattermostFileInfo,
	MattermostPost,
	MattermostPostList,
	MattermostTeam,
	MattermostUser,
} from "./mattermost/schemas.ts";
export {
	type EvidenceAttachment,
	type EvidencePost,
	type PackedPost,
	type PackedThread,
	type PackThreadOptions,
	packThread,
	renderedAttachmentUnits,
	renderedPostUnits,
} from "./packing.ts";
export {
	type CommandResult,
	SCHEMA_VERSION,
	type StableError,
	type Warning,
} from "./results.ts";
export {
	classifySubject,
	configuredConversations,
	directCandidate,
	type MattermostSubject,
	type RankingReason,
	type RetrievalProbe,
	type RoutedConversation,
	type RoutingEvidenceType,
	type RoutingResult,
	resolveProbes,
	routeConversations,
	type SearchMatch,
	type SearchResult,
	searchThreads,
	type ThreadCandidate,
	widenedRouting,
} from "./retrieval.ts";
export {
	type ChannelValidationResult,
	type ConfiguredConversationsResult,
	type ConfiguredDirectMessageResult,
	type DoctorCheck,
	type DoctorResult,
	listConfiguredConversations,
	runDoctor,
	type ValidationItem,
	validateConfiguredConversations,
} from "./setup.ts";
export {
	buildFtsProbe,
	type ConversationKind,
	type ConversationRecord,
	databaseFilePaths,
	type IndexedFile,
	type IndexedPost,
	type IndexedUser,
	MattermostStore,
	type PageWrite,
	type SyncCheckpoint,
	type TicketThreadRelationship,
} from "./storage.ts";
export {
	type ConversationFreshness,
	type ConversationSyncResult,
	inspectFreshness,
	reconcileStaleConversations,
	resolveConversations,
	type SyncClient,
	type SyncOptions,
	type SyncResult,
	syncConfiguredConversations,
} from "./sync.ts";
export {
	containsNormalizedText,
	normalizeSearchText,
	STOP_WORDS,
} from "./text.ts";
